[
  {
    id: 1,
    ism: "Azizbek",
    familiya: "Karimov",
    tugilganJoy: "Toshkent",
    tugilganYili: 1988,
    yoshi: 38,
    tugilganKuni: "12-mart",
    jinsi: "erkak",
    messengerlari: ["Telegram", "WhatsApp"],
    telefonRaqami: "+998901112233",
    ishlashJoy: "IT Park Toshkent",
    email: "aziz.karimov@gmail.com",
    oilasi: {
      ayoli: "Malika Karimova",
      bolalari: [
        {
          ism: "Muhammadali",
          yoshi: 10,
          maktabi: "45-maktab",
          qiziqishi: "Futbol",
        },
        {
          ism: "Zahro",
          yoshi: 6,
          bogchasi: "Quyoshcha",
          qiziqishi: "Rasm chizish",
        },
      ],
    },
    mashinalari: ["Malibu 2", "Cobalt"],
    boyligi: 150000,
    capitali: "AQSH dollari",
  },
  {
    id: 2,
    ism: "Dilshod",
    familiya: "Raxmonov",
    tugilganJoy: "Samarqand",
    tugilganYili: 1992,
    yoshi: 34,
    tugilganKuni: "5-iyul",
    jinsi: "erkak",
    messengerlari: ["Telegram"],
    telefonRaqami: "+998933334455",
    ishlashJoy: "Samarqand Bank",
    email: "dilshod.r@gmail.com",
    oilasi: {
      ayoli: "Gulnoza Raxmonova",
      bolalari: [
        {
          ism: "Imron",
          yoshi: 4,
          bogchasi: "Bolajon",
          qiziqishi: "Mashinalar",
        },
      ],
    },
    mashinalari: ["Tracker"],
    boyligi: 80000,
    capitali: "AQSH dollari",
  },
  {
    id: 3,
    ism: "Shahnoza",
    familiya: "Tosheva",
    tugilganJoy: "Buxoro",
    tugilganYili: 1995,
    yoshi: 31,
    tugilganKuni: "18-yanvar",
    jinsi: "ayol",
    messengerlari: ["Telegram", "Instagram"],
    telefonRaqami: "+998998887766",
    ishlashJoy: "Buxoro Universiteti",
    email: "shahnoza.t@gmail.com",
    oilasi: {
      eri: "Bekzod Toshev",
      bolalari: [],
    },
    mashinalari: ["Spark"],
    boyligi: 50000,
    capitali: "AQSH dollari",
  },
  {
    id: 4,
    ism: "Javlon",
    familiya: "Ismoilov",
    tugilganJoy: "Andijon",
    tugilganYili: 1985,
    yoshi: 41,
    tugilganKuni: "22-fevral",
    jinsi: "erkak",
    messengerlari: ["WhatsApp"],
    telefonRaqami: "+998977771122",
    ishlashJoy: "Andijon Tekstil",
    email: "javlon.i@gmail.com",
    oilasi: {
      ayoli: "Nigora Ismoilova",
      bolalari: [
        {
          ism: "Asadbek",
          yoshi: 14,
          maktabi: "12-maktab",
          qiziqishi: "Kurash",
        },
        { ism: "Madina", yoshi: 9, maktabi: "12-maktab", qiziqishi: "Musiqa" },
      ],
    },
    mashinalari: ["Gentra"],
    boyligi: 120000,
    capitali: "AQSH dollari",
  },
  {
    id: 5,
    ism: "Sarvinoz",
    familiya: "Abdullayeva",
    tugilganJoy: "Namangan",
    tugilganYili: 1990,
    yoshi: 36,
    tugilganKuni: "9-aprel",
    jinsi: "ayol",
    messengerlari: ["Telegram"],
    telefonRaqami: "+998901234567",
    ishlashJoy: "Namangan Clinic",
    email: "sarvinoz.a@gmail.com",
    oilasi: {
      eri: "Otabek Abdullayev",
      bolalari: [
        { ism: "Oybek", yoshi: 7, maktabi: "5-maktab", qiziqishi: "Shaxmat" },
      ],
    },
    mashinalari: ["Kia K5"],
    boyligi: 95000,
    capitali: "AQSH dollari",
  },
  {
    id: 6,
    ism: "Bekzod",
    familiya: "Nazarov",
    tugilganJoy: "Farg'ona",
    tugilganYili: 1987,
    yoshi: 39,
    tugilganKuni: "30-avgust",
    jinsi: "erkak",
    messengerlari: ["Telegram", "Facebook"],
    telefonRaqami: "+998934445566",
    ishlashJoy: "Farg'ona Neft",
    email: "bekzod.n@gmail.com",
    oilasi: {
      ayoli: "Dilafruz Nazarova",
      bolalari: [],
    },
    mashinalari: ["Toyota Prado"],
    boyligi: 200000,
    capitali: "AQSH dollari",
  },
  {
    id: 7,
    ism: "Madina",
    familiya: "Qodirova",
    tugilganJoy: "Xiva",
    tugilganYili: 1998,
    yoshi: 28,
    tugilganKuni: "14-iyun",
    jinsi: "ayol",
    messengerlari: ["Instagram"],
    telefonRaqami: "+998977009900",
    ishlashJoy: "Xiva Tourism",
    email: "madina.q@gmail.com",
    oilasi: {
      eri: null,
      bolalari: [],
    },
    mashinalari: [],
    boyligi: 40000,
    capitali: "AQSH dollari",
  },
  {
    id: 8,
    ism: "Sherzod",
    familiya: "Yuldashev",
    tugilganJoy: "Nukus",
    tugilganYili: 1991,
    yoshi: 35,
    tugilganKuni: "2-dekabr",
    jinsi: "erkak",
    messengerlari: ["Telegram"],
    telefonRaqami: "+998912223344",
    ishlashJoy: "Qoraqalpoq Energiya",
    email: "sherzod.y@gmail.com",
    oilasi: {
      ayoli: "Zarina Yuldasheva",
      bolalari: [
        { ism: "Samir", yoshi: 3, bogchasi: "Tong", qiziqishi: "O'yinchoqlar" },
      ],
    },
    mashinalari: ["Damas"],
    boyligi: 60000,
    capitali: "AQSH dollari",
  },
  {
    id: 9,
    ism: "Kamola",
    familiya: "Saidova",
    tugilganJoy: "Jizzax",
    tugilganYili: 1993,
    yoshi: 33,
    tugilganKuni: "11-sentyabr",
    jinsi: "ayol",
    messengerlari: ["Telegram", "WhatsApp"],
    telefonRaqami: "+998935556677",
    ishlashJoy: "Jizzax School",
    email: "kamola.s@gmail.com",
    oilasi: {
      eri: "Anvar Saidov",
      bolalari: [
        {
          ism: "Ali",
          yoshi: 8,
          maktabi: "3-maktab",
          qiziqishi: "Robototexnika",
        },
      ],
    },
    mashinalari: ["Spark"],
    boyligi: 70000,
    capitali: "AQSH dollari",
  },
  {
    id: 10,
    ism: "Rustam",
    familiya: "Xolmatov",
    tugilganJoy: "Qarshi",
    tugilganYili: 1983,
    yoshi: 43,
    tugilganKuni: "27-may",
    jinsi: "erkak",
    messengerlari: ["Telegram"],
    telefonRaqami: "+998998001122",
    ishlashJoy: "Qarshi Qurilish",
    email: "rustam.x@gmail.com",
    oilasi: {
      ayoli: "Lola Xolmatova",
      bolalari: [
        {
          ism: "Jasur",
          yoshi: 16,
          maktabi: "10-maktab",
          qiziqishi: "Basketbol",
        },
        { ism: "Sevinch", yoshi: 12, maktabi: "10-maktab", qiziqishi: "Raqs" },
      ],
    },
    mashinalari: ["BMW X5"],
    boyligi: 300000,
    capitali: "AQSH dollari",
  },
];
